-- UTILITIES -- DANIEL
-- drop database
DROP DATABASE PROJ_INFO_330_B7

-- backup database
BACKUP DATABASE PROJ_INFO_330_B7 TO DISK = 'C:\SQL\PROJ_INFO_330_B7.bak'
BACKUP DATABASE PROJ_INFO_330_B7 TO DISK = 'C:\SQL\PROJ_INFO_330_B7.bak' WITH DIFFERENTIAL
